baseurl      = "https://jeykey.net"
title        = "Jakob Klemm - Database"
languageCode = "en-us"
theme        = "anubis"
paginate     = 5

[author]
name = "Jakob Klemm"

[params]
author = "Jakob Klemm"
description = "Personal knowledge database"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "dark"
readMore = false

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
