#+TITLE: Habits

Most of what we do on a day to day basis isn't something we want to
do. We do it because we hope that it can help us to achieve what we
really want. Most habits and actions are in a sens just obstacles. We
only really want what the habit or action produces or delivers.

In order to learn new habits and keep repeating existing ones a few
things are important: Habits are triggered by cues, so it is important
to [[file:make_it_obvious.org][Make it obvious]]. Once a habit is triggered it is important to give
a reason to do it, to [[file:make_it_attractive.org][Make it attractive]]. Humans always chose the path
of least resistance, meaning just because something is attractive, it
might not be enough to trick ourselves into doing it. That's why it is
important to [[file:make_it_easy][Make it easy]].

Up to now we have looked at tactics to get us started with a habit and
actually do it. But what turns actions into habits is repetition. In
order to stay consistent with our habits, we need to [[file:make_it_satisfying.org][Make it satisfying]].

In case the system ever breaks down and the chain of repetitions is
broken, it is important to follow the [[file:two_day_rule.org][Two-Day Rule]] for an easy
recovery.
