#+title: Make it easy

Most of the time we are so focused on how to do something in the
optimal way, that we don't actually do it. James Clear describes it as
[[file:motion_or_action.org][Motion or Action]]. You feel like you are getting something done, but
your actually only planning to get something done.

But why aren't all habits easy?
Humans always choose the path of least resistance. They always try to
minimize [[file:friction.org][Friction]].

A lot of the decisions we make every day are just habits. While we do
the more influential, important ones consciously, the habits that came
before them influenced the situation in which the important decisions
have to be made. A habit that can be completed in just a few seconds
can influence every decision that comes after it. Each day there are a
few [[file:decisive_moments.org][Decisive moments]], that influence the rest of the day.

Instead of trying to master something instantly or learning a
complicated habit, it might be helpful to start with something
simpler, following [[file:two_minute_rule.org][Two-Minute Rule]].

Instead of making a good habit easy it might also be important to make
a bad habit difficult: [[file:make_it_difficult.org][Make it difficult]].
