#+title: Make it satisfying
*Cardinal Rule of Behavior*: /What is rewarded is repeated. What is
punished is avoided./

The habits that stick and the tasks that we repeat are determined by
what we are rewarded for now. Sadly most habits that we would consider
/useful/ don't have instant rewards. Instead they need to be repeated in
order for the effects to show. Even worse: a lot of bad habits have
instant gratification, while a lot of good habits don't. In order to
adapt good habits and stick with them we need to [[file:sacrifice.org][Sacrifice]] and wait
for our delayed gratification.

If we were perfectly rational this wouldn't be that hard. Most bad
habits that have an instant reward now tend to have negative
consequences in the future, while good habits are the opposite. But
our brains are trained to prioritize instant rewards over delayed
rewards.
#+begin_quote
As a general rule, the more immediate pleasure you get from an action,
the more strongly you should question whether it aligns with your
long-term goals. James Clear (Atomic Habits, P.189)
#+end_quote

To actually stick with habits it is important that their ending is in
some way satisfying. Similarly to [[file:habit_stacking.org][Habit stacking]], where you attach the
beginning of a habit to something, it can be helpful to attach some
kind of reward to the end of one. This does not have to happen for
ever, since at some point the delayed gratification starts setting in,
making the immediate rewards obsolete.

An easy method to reliably stick with bad habits is to use a [[file:habit_tracker.org][Habit
tracker]], making the progress easily measurable.
